"""rename address

Revision ID: 62652c4c5f95
Revises: 3147887675c2
Create Date: 2026-03-04 12:21:15.092686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62652c4c5f95'
down_revision = '3147887675c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
